=== [ #1 System ] / [system]
==== Logging / [enable_logging]
Specify whether to enable log output. System initialization logs for Automatics are always output regardless of the value of this option.

- Default value: false

==== Log Level To Allow Logging / [log_level_to_allow_logging]
Specify the log level that allows logging.

- Default value: Fatal, Error, Warning, Message
- Acceptable values: None, Fatal, Error, Warning, Message, Info, Debug, All
- Multiple values can be set at the same time by separating them with , (e.g. Fatal, Error)

==== Resources Directory / [resources_directory]
Specify the absolute path of the directory where your custom translation files and resources such as custom map icons are stored. If a valid value is specified for this option, the default resource directory (the same directory as Automations.dll) is followed by the resources stored in this directory.

- Default value:

=== [ #2 Automatic Door ] / [automatic_door]
==== Automatic Door / [enable_automatic_door]
Specify whether to enable the feature that automatically opens and closes the door.

- Default value: true

==== Allow Automatic Door / [allow_automatic_door]
Specify which doors are allowed to open and close automatically.

- Default value: WoodDoor, WoodGate, IronGate, DarkwoodGate
- Acceptable values: None, WoodDoor, WoodGate, IronGate, DarkwoodGate, WoodShutter, All
- Multiple values can be set at the same time by separating them with , (e.g. WoodDoor, WoodGate)

==== Allow Automatic Door (Custom) / [allow_automatic_door_custom]
Specify the display or internal name of any door that is allowed to open and close automatically. A display name is a name displayed in the game, such as "Wood door", and the specified value will enable the automatic door if it partially matches the target display name. The internal name is the name used on the program side, such as "$piece_wooddoor", and the specified value must exactly match the target's internal name for the automatic door to be enabled.

- Default value:

==== Interval To Open / [interval_to_open]
Specify the interval at which the process of automatically opening the door is called. If set to less than 0.1, the function to automatically open the door will be disabled. (Unit: second)

- Default value: 0.1
- Acceptable value range: From 0 to 8

==== Interval To Close / [interval_to_close]
Specify the interval at which the process of automatically closing the door is called. If set to less than 0.1, the function to automatically close the door will be disabled. (Unit: second)

- Default value: 0.1
- Acceptable value range: From 0 to 8

==== Distance For Automatic Opening / [distance_for_automatic_opening]
Specify how close the player must be to the door in order for it to open automatically. (Unit: meter)

- Default value: 2.5
- Acceptable value range: From 1 to 8

==== Distance For Automatic Closing / [distance_for_automatic_closing]
Specify how far the player must be from the door for the door to close automatically. (Unit: meter)

- Default value: 2.5
- Acceptable value range: From 1 to 8

==== Automatic Door Enable/Disable Toggle / [automatic_door_enable_disable_toggle]
Specify a shortcut key to enable/disable the automatic door.

- Default value:

==== Automatic Door Enable/Disable Toggle Message / [automatic_door_enable_disable_toggle_message]
Specify where a message is displayed when the automatic door is enabled or disabled by a shortcut key.

- Default value: Center
- Acceptable values: None, Center, TopLeft

=== [ #3 Automatic Mapping ] / [automatic_mapping]
==== Automatic Mapping / [enable_automatic_mapping]
Specify whether to enable the feature that automatically pinning objects and locations to the map.

- Default value: true

==== Dynamic Object Search Range / [dynamic_object_search_range]
Specify the range of dynamic objects to be explored. "Dynamic Object" are objects that change position, such as animals, monsters, etc. Set to 0 to disable pinning of dynamic objects. (Unit: meter)

- Default value: 64
- Acceptable value range: From 0 to 256

==== Static Object Search Range / [static_object_search_range]
Specify the range of static objects to be explored. "Static Object" are objects that do not change their position, such as plants, deposit, etc. Setting this to 0 disables pinning of static objects. (Unit: meter)

- Default value: 16
- Acceptable value range: From 0 to 256

==== Location Search Range / [location_search_range]
Specify the range of location to be explored. "Location" is a specific place, such as dungeon, fuling village, etc. Setting this to 0 disables location pinning. (Unit: meter)

- Default value: 96
- Acceptable value range: From 0 to 256

==== Allow Pinning Animal / [allow_pinning_animal]
Specify the animals to be automatic pinning.

- Default value: All
- Acceptable values: None, Boar, Deer, Wolf, Lox, Bird, Fish, All
- Multiple values can be set at the same time by separating them with , (e.g. Boar, Deer)

==== Allow Pinning Animal (Custom) / [allow_pinning_animal_custom]
Specify the display or internal name of any animals that is allowed to automatic map pinning. A display name is the name displayed in the game, such as "Boar", and the specified value will enable the pinning if it partially matches the target display name. Internal name is the name used on the program side, such as "$enemy_boar", and the specified value must exactly match the target's internal name for the pinning to be enabled.

- Default value:

==== Allow Pinning Monster / [allow_pinning_monster]
Specify the monsters to be automatic pinning.

- Default value: All
- Acceptable values: None, Greyling, Neck, Ghost, Greydwarf, GreydwarfBrute, GreydwarfShaman, RancidRemains, Skeleton, Troll, Abomination, Blob, Draugr, DraugrElite, Leech, Oozer, Surtling, Wraith, Drake, Fenring, StoneGolem, Deathsquito, Fuling, FulingBerserker, FulingShaman, Growth, Serpent, Bat, FenringCultist, Ulv, All
- Multiple values can be set at the same time by separating them with , (e.g. Greyling, Neck)

==== Allow Pinning Monster (Custom) / [allow_pinning_monster_custom]
Specify the display or internal name of any monster that is allowed to automatic map pinning. A display name is the name displayed in the game, such as "Greyling", and the specified value will enable the pinning if it partially matches the target display name. Internal name is the name used on the program side, such as "$enemy_greyling", and the specified value must exactly match the target's internal name for the pinning to be enabled.

- Default value:

==== Allow Pinning Flora / [allow_pinning_flora]
Specify the flora to be automatic pinning.

- Default value: Mushroom, Raspberries, Blueberries, CarrotSeeds, Thistle, TurnipSeeds, Cloudberries
- Acceptable values: None, Dandelion, Mushroom, Raspberries, Blueberries, Carrot, CarrotSeeds, YellowMushroom, Thistle, Turnip, TurnipSeeds, Onion, OnionSeeds, Barley, Cloudberries, Flex, All
- Multiple values can be set at the same time by separating them with , (e.g. Dandelion, Mushroom)

==== Allow Pinning Flora (Custom) / [allow_pinning_flora_custom]
Specify the display or internal name of any flora that is allowed to automatic map pinning. A display name is the name displayed in the game, such as "Dandelion", and the specified value will enable the pinning if it partially matches the target display name. Internal name is the name used on the program side, such as "$item_dandelion", and the specified value must exactly match the target's internal name for the pinning to be enabled.

- Default value:

==== Allow Pinning Deposit / [allow_pinning_deposit]
Specify the deposit to be automatic pinning.

- Default value: CopperDeposit, TinDeposit, MudPile, SilverVein
- Acceptable values: None, CopperDeposit, TinDeposit, MudPile, ObsidianDeposit, SilverVein, All
- Multiple values can be set at the same time by separating them with , (e.g. CopperDeposit, TinDeposit)

==== Allow Pinning Deposit (Custom) / [allow_pinning_deposit_custom]
Specify the display or internal name of any deposit that is allowed to automatic map pinning. A display name is the name displayed in the game, such as "Copper deposit", and the specified value will enable the pinning if it partially matches the target display name. Internal name is the name used on the program side, such as "$piece_deposit_copper", and the specified value must exactly match the target's internal name for the pinning to be enabled.

- Default value:

==== Allow Pinning Spawner / [allow_pinning_spawner]
Specify the spawners to be automatic pinning.

- Default value: None
- Acceptable values: None, GreydwarfNest, EvilBonePile, BodyPile, All
- Multiple values can be set at the same time by separating them with , (e.g. GreydwarfNest, EvilBonePile)

==== Allow Pinning Spawner (Custom) / [allow_pinning_spawner_custom]
Specify the display or internal name of any spawners that is allowed to automatic map pinning. A display name is the name displayed in the game, such as "Greydwarf nest", and the specified value will enable the pinning if it partially matches the target display name. Internal name is the name used on the program side, such as "$enemy_greydwarfspawner", and the specified value must exactly match the target's internal name for the pinning to be enabled.

- Default value:

==== Allow Pinning Other Object / [allow_pinning_other]
Specify the other objects to be automatic pinning.

- Default value: WildBeehive
- Acceptable values: None, Vegvisir, Runestone, WildBeehive, Portal, All
- Multiple values can be set at the same time by separating them with , (e.g. Vegvisir, Runestone)

==== Allow Pinning Other Object (Custom) / [allow_pinning_other_custom]
Specify the display or internal name of any other objects that is allowed to automatic map pinning. A display name is the name displayed in the game, such as "Oak", and the specified value will enable the pinning if it partially matches the target display name. Internal name is the name used on the program side, such as "$prop_oak", and the specified value must exactly match the target's internal name for the pinning to be enabled.

- Default value:

==== Allow Pinning Dungeon / [allow_pinning_dungeon]
Specify the dungeons to be automatic pinning.

- Default value: All
- Acceptable values: None, BurialChambers, TrollCave, SunkenCrypts, MountainCave, All
- Multiple values can be set at the same time by separating them with , (e.g. BurialChambers, TrollCave)

==== Allow Pinning Dungeon (Custom) / [allow_pinning_dungeon_custom]
Specify the prefab name of the any dungeon as a string or regular expression. The prefab name is the name given to the dungeon's appearance object. (e.g. Crypt2, TrollCave, SunkenCrypt1); If a string is specified, pinning is allowed if it is a partial match to the target prefab name. If a regular expression is specified, pinning is allowed if the target prefab name matches the regular expression. The regular expression must be prefixed with "r/"

- Default value:

==== Allow Pinning Spot / [allow_pinning_spot]
Specify the spots to be automatic pinning.

- Default value: All
- Acceptable values: None, InfestedTree, FireHole, DrakeNest, GoblinCamp, TarPit, All
- Multiple values can be set at the same time by separating them with , (e.g. InfestedTree, FireHole)

==== Allow Pinning Spot (Custom) / [allow_pinning_spot_custom]
Specify the prefab name of the any spot as a string or regular expression. The prefab name is the name given to the spot's structure. (e.g. AbandonedLogCabin02, Dolmen01, ShipWreck01); If a string is specified, pinning is allowed if it is a partial match to the target prefab name. If a regular expression is specified, pinning is allowed if the target prefab name matches the regular expression. The regular expression must be prefixed with "r/"

- Default value:

==== Allow Pinning Ship / [allow_pinning_ship]
Enable automatic pinning for the ship.

- Default value: true

==== Not Pinning Tamed Animals / [not_pinning_tamed_animals]
Exclude tamed animals from automatic pinning.

- Default value: true

==== Static Object Search Interval / [static_object_search_interval]
Specify the interval at which static object search. Setting to 0 disables periodic static object search. (Unit: second)

- Default value: 0.25
- Acceptable value range: From 0 to 8

==== Flora Pins Merge Range / [flora_pins_merge_range]
When pinning flora, it recursively searches for the same flora that exist within a specified range and merge them into a single pin. (Unit: meter)

- Default value: 8
- Acceptable value range: From 0 to 16

==== Need To Equip Wishbone For Underground Deposits / [need_to_equip_wishbone_for_underground_deposits]
Specify whether the wishbone needs to be equipped to attempt to pinning underground deposits.

- Default value: true

==== Static Object Search / [static_object_search_key]
Specify shortcut keys for searching static objects. Setting this item disables the static object search at regular intervals, so that it is performed only once each time the shortcut key is pressed.

- Default value:

=== [ #4 Automatic Processing ] / [automatic_processing]
==== Automatic Processing / [enable_automatic_processing]
Specify whether to enable or disable the ability to automatically perform tasks such as cooking, refining, and refuel.

- Default value: true

==== Allow Processing By Beehive / [allow_processing_by_piece_beehive]
Specify the automatic processing to be allowed for Beehive

- Default value: Store
- Acceptable values: None, Store

==== Container Search Range By Beehive / [container_search_range_by_piece_beehive]
Specify the maximum distance which Beehive will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Product Count Of Suppress Processing For Beehive / [piece_beehive_product_count_of_suppress_processing]
Suppresses automatic processing of Beehive to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Allow Processing By Bonfire / [allow_processing_by_piece_bonfire]
Specify the automatic processing to be allowed for Bonfire

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Bonfire / [container_search_range_by_piece_bonfire]
Specify the maximum distance which Bonfire will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Bonfire / [piece_bonfire_fuel_count_of_suppress_processing]
Suppresses automatic processing of Bonfire to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Allow Processing By Blast furnace / [allow_processing_by_piece_blastfurnace]
Specify the automatic processing to be allowed for Blast furnace

- Default value: All
- Acceptable values: None, Craft, Refuel, Store, All
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Refuel)

==== Container Search Range By Blast furnace / [container_search_range_by_piece_blastfurnace]
Specify the maximum distance which Blast furnace will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Blast furnace / [piece_blastfurnace_material_count_of_suppress_processing]
Suppresses automatic processing of Blast furnace to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Fuel Count Of Suppress Processing For Blast furnace / [piece_blastfurnace_fuel_count_of_suppress_processing]
Suppresses automatic processing of Blast furnace to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Product Count Of Suppress Processing For Blast furnace / [piece_blastfurnace_product_count_of_suppress_processing]
Suppresses automatic processing of Blast furnace to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Refuel Blast furnace Only When Materials Supplied / [piece_blastfurnace_refuel_only_when_materials_supplied]
Performs automatic refuel only when materials are supplied to Blast furnace.

- Default value: false

==== Allow Processing By Campfire / [allow_processing_by_piece_firepit]
Specify the automatic processing to be allowed for Campfire

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Campfire / [container_search_range_by_piece_firepit]
Specify the maximum distance which Campfire will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Campfire / [piece_firepit_fuel_count_of_suppress_processing]
Suppresses automatic processing of Campfire to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Allow Processing By Charcoal kiln / [allow_processing_by_piece_charcoalkiln]
Specify the automatic processing to be allowed for Charcoal kiln

- Default value: Craft, Store
- Acceptable values: None, Craft, Store
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Container Search Range By Charcoal kiln / [container_search_range_by_piece_charcoalkiln]
Specify the maximum distance which Charcoal kiln will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Charcoal kiln / [piece_charcoalkiln_material_count_of_suppress_processing]
Suppresses automatic processing of Charcoal kiln to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Product Count Of Suppress Processing For Charcoal kiln / [piece_charcoalkiln_product_count_of_suppress_processing]
Suppresses automatic processing of Charcoal kiln to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Allow Processing By Cooking station / [allow_processing_by_piece_cookingstation]
Specify the automatic processing to be allowed for Cooking station

- Default value: Store
- Acceptable values: None, Craft, Store
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Container Search Range By Cooking station / [container_search_range_by_piece_cookingstation]
Specify the maximum distance which Cooking station will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Cooking station / [piece_cookingstation_material_count_of_suppress_processing]
Suppresses automatic processing of Cooking station to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Product Count Of Suppress Processing For Cooking station / [piece_cookingstation_product_count_of_suppress_processing]
Suppresses automatic processing of Cooking station to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Allow Processing By Fermenter / [allow_processing_by_piece_fermenter]
Specify the automatic processing to be allowed for Fermenter

- Default value: Craft, Store
- Acceptable values: None, Craft, Store
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Container Search Range By Fermenter / [container_search_range_by_piece_fermenter]
Specify the maximum distance which Fermenter will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Fermenter / [piece_fermenter_material_count_of_suppress_processing]
Suppresses automatic processing of Fermenter to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Product Count Of Suppress Processing For Fermenter / [piece_fermenter_product_count_of_suppress_processing]
Suppresses automatic processing of Fermenter to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Allow Processing By Hanging brazier / [allow_processing_by_piece_brazierceiling01]
Specify the automatic processing to be allowed for Hanging brazier

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Hanging brazier / [container_search_range_by_piece_brazierceiling01]
Specify the maximum distance which Hanging brazier will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Hanging brazier / [piece_brazierceiling01_fuel_count_of_suppress_processing]
Suppresses automatic processing of Hanging brazier to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Allow Processing By Hearth / [allow_processing_by_piece_hearth]
Specify the automatic processing to be allowed for Hearth

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Hearth / [container_search_range_by_piece_hearth]
Specify the maximum distance which Hearth will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Hearth / [piece_hearth_fuel_count_of_suppress_processing]
Suppresses automatic processing of Hearth to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Allow Processing By Iron cooking station / [allow_processing_by_piece_cookingstation_iron]
Specify the automatic processing to be allowed for Iron cooking station

- Default value: Store
- Acceptable values: None, Craft, Store
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Container Search Range By Iron cooking station / [container_search_range_by_piece_cookingstation_iron]
Specify the maximum distance which Iron cooking station will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Iron cooking station / [piece_cookingstation_iron_material_count_of_suppress_processing]
Suppresses automatic processing of Iron cooking station to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Product Count Of Suppress Processing For Iron cooking station / [piece_cookingstation_iron_product_count_of_suppress_processing]
Suppresses automatic processing of Iron cooking station to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Allow Processing By Jack-o-turnip / [allow_processing_by_piece_jackoturnip]
Specify the automatic processing to be allowed for Jack-o-turnip

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Jack-o-turnip / [container_search_range_by_piece_jackoturnip]
Specify the maximum distance which Jack-o-turnip will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Jack-o-turnip / [piece_jackoturnip_fuel_count_of_suppress_processing]
Suppresses automatic processing of Jack-o-turnip to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Allow Processing By Sconce / [allow_processing_by_piece_sconce]
Specify the automatic processing to be allowed for Sconce

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Sconce / [container_search_range_by_piece_sconce]
Specify the maximum distance which Sconce will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Sconce / [piece_sconce_fuel_count_of_suppress_processing]
Suppresses automatic processing of Sconce to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Allow Processing By Smelter / [allow_processing_by_piece_smelter]
Specify the automatic processing to be allowed for Smelter

- Default value: All
- Acceptable values: None, Craft, Refuel, Store, All
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Refuel)

==== Container Search Range By Smelter / [container_search_range_by_piece_smelter]
Specify the maximum distance which Smelter will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Smelter / [piece_smelter_material_count_of_suppress_processing]
Suppresses automatic processing of Smelter to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Fuel Count Of Suppress Processing For Smelter / [piece_smelter_fuel_count_of_suppress_processing]
Suppresses automatic processing of Smelter to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Product Count Of Suppress Processing For Smelter / [piece_smelter_product_count_of_suppress_processing]
Suppresses automatic processing of Smelter to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Refuel Smelter Only When Materials Supplied / [piece_smelter_refuel_only_when_materials_supplied]
Performs automatic refuel only when materials are supplied to Smelter.

- Default value: false

==== Allow Processing By Spinning wheel / [allow_processing_by_piece_spinningwheel]
Specify the automatic processing to be allowed for Spinning wheel

- Default value: Store
- Acceptable values: None, Craft, Store
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Container Search Range By Spinning wheel / [container_search_range_by_piece_spinningwheel]
Specify the maximum distance which Spinning wheel will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Spinning wheel / [piece_spinningwheel_material_count_of_suppress_processing]
Suppresses automatic processing of Spinning wheel to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Product Count Of Suppress Processing For Spinning wheel / [piece_spinningwheel_product_count_of_suppress_processing]
Suppresses automatic processing of Spinning wheel to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Allow Processing By Standing blue-burning iron torch / [allow_processing_by_piece_groundtorchblue]
Specify the automatic processing to be allowed for Standing blue-burning iron torch

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Standing blue-burning iron torch / [container_search_range_by_piece_groundtorchblue]
Specify the maximum distance which Standing blue-burning iron torch will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Standing blue-burning iron torch / [piece_groundtorchblue_fuel_count_of_suppress_processing]
Suppresses automatic processing of Standing blue-burning iron torch to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Allow Processing By Standing brazier / [allow_processing_by_piece_brazierfloor01]
Specify the automatic processing to be allowed for Standing brazier

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Standing brazier / [container_search_range_by_piece_brazierfloor01]
Specify the maximum distance which Standing brazier will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Standing brazier / [piece_brazierfloor01_fuel_count_of_suppress_processing]
Suppresses automatic processing of Standing brazier to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Allow Processing By Standing green-burning iron torch / [allow_processing_by_piece_groundtorchgreen]
Specify the automatic processing to be allowed for Standing green-burning iron torch

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Standing green-burning iron torch / [container_search_range_by_piece_groundtorchgreen]
Specify the maximum distance which Standing green-burning iron torch will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Standing green-burning iron torch / [piece_groundtorchgreen_fuel_count_of_suppress_processing]
Suppresses automatic processing of Standing green-burning iron torch to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Allow Processing By Standing iron torch / [allow_processing_by_piece_groundtorch]
Specify the automatic processing to be allowed for Standing iron torch

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Standing iron torch / [container_search_range_by_piece_groundtorch]
Specify the maximum distance which Standing iron torch will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Standing iron torch / [piece_groundtorch_fuel_count_of_suppress_processing]
Suppresses automatic processing of Standing iron torch to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Allow Processing By Standing wood torch / [allow_processing_by_piece_groundtorchwood]
Specify the automatic processing to be allowed for Standing wood torch

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Standing wood torch / [container_search_range_by_piece_groundtorchwood]
Specify the maximum distance which Standing wood torch will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Standing wood torch / [piece_groundtorchwood_fuel_count_of_suppress_processing]
Suppresses automatic processing of Standing wood torch to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Allow Processing By Stone oven / [allow_processing_by_piece_oven]
Specify the automatic processing to be allowed for Stone oven

- Default value: All
- Acceptable values: None, Craft, Refuel, Store, All
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Refuel)

==== Container Search Range By Stone oven / [container_search_range_by_piece_oven]
Specify the maximum distance which Stone oven will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Stone oven / [piece_oven_material_count_of_suppress_processing]
Suppresses automatic processing of Stone oven to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Fuel Count Of Suppress Processing For Stone oven / [piece_oven_fuel_count_of_suppress_processing]
Suppresses automatic processing of Stone oven to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Product Count Of Suppress Processing For Stone oven / [piece_oven_product_count_of_suppress_processing]
Suppresses automatic processing of Stone oven to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Refuel Stone oven Only When Materials Supplied / [piece_oven_refuel_only_when_materials_supplied]
Performs automatic refuel only when materials are supplied to Stone oven.

- Default value: false

==== Allow Processing By Windmill / [allow_processing_by_piece_windmill]
Specify the automatic processing to be allowed for Windmill

- Default value: Store
- Acceptable values: None, Craft, Store
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Container Search Range By Windmill / [container_search_range_by_piece_windmill]
Specify the maximum distance which Windmill will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Windmill / [piece_windmill_material_count_of_suppress_processing]
Suppresses automatic processing of Windmill to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Product Count Of Suppress Processing For Windmill / [piece_windmill_product_count_of_suppress_processing]
Suppresses automatic processing of Windmill to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

=== [ #5 Automatic Feeding ] / [automatic_feeding]
==== Automatic Feeding / [enable_automatic_feeding]
Specify whether to enable the feature for animals to automatically consume feed items from players and containers.

- Default value: true

==== Feed Search Range / [feed_search_range]
Specify the range in which the animal searches for food. If set to 0, the default value for each animal will be used. (Unit: meter)

- Default value: 0
- Acceptable value range: From 0 to 64

==== Need Get Close To Eat The Feed / [need_get_close_to_eat_the_feed]
Specify whether the animal needs to approach the container or player to eat the feed.

- Default value: false

==== Allow To Feed From Container / [allow_to_feed_from_container]
Specify the types of animals allowed to feed from the container.

- Default value: Tamed
- Acceptable values: None, Wild, Tamed, All
- Multiple values can be set at the same time by separating them with , (e.g. Wild, Tamed)

=== [ #6 Automatic Repair ] / [automatic_repair]
==== Automatic Repair / [enable_automatic_repair]
Specify whether to enable the feature that automatically repair items and pieces.

- Default value: true

==== Crafting Station Search Range / [crafting_station_search_range]
Specify the range to search for a crafting station to be used to repair items. Setting to 0 disables periodic item repair. (Unit: meters)

- Default value: 16
- Acceptable value range: From 0 to 64

==== Repair Items When Accessing The Crafting Station / [repair_items_when_accessing_the_crafting_station]
Specify whether or not to repair all items that can be repaired when the workbench GUI is opened.

- Default value: false

==== Item Repair Message / [item_repair_message]
Specify where the message is displayed when an item is repaired.

- Default value: None
- Acceptable values: None, Center, TopLeft

==== Piece Search Range / [piece_search_range]
Specify the range to search for a pieces to repair. Setting to 0 disables periodic pieces repairs. (Unit: meters)

- Default value: 16
- Acceptable value range: From 0 to 64

==== Piece Repair Message / [piece_repair_message]
Specify where the message is displayed when a piece is repaired.

- Default value: None
- Acceptable values: None, Center, TopLeft

=== [ #7 Automatic Mining ] / [automatic_mining]
==== Automatic Mining / [enable_automatic_mining]
Specify whether to enable the feature that mine minerals automatically.

- Default value: true

==== Need To Equip Pickaxe For Mining / [need_to_equip_pickaxe]
Specify whether a pickaxe needs to be equipped to attempt automatic mining. Disabling this option will use the most advanced pickaxe in the player's inventory. If there is no pickaxe in the player's inventory, automatic mining will not be attempted.

- Default value: true

==== Mining Interval / [mining_interval]
Specify the interval between mining attempts. (Unit: seconds)

- Default value: 1.5
- Acceptable value range: From 0.1 to 4

==== Attempt Mining / [mining_key]
Specify a shortcut key to attempt mining. If a valid shortcut key is assigned to this option, mining at regular intervals is disabled.

- Default value:

==== Mining Range / [mining_range]
Specify the maximum distance to search for a mineral. Setting to 0 the pickaxe's attack range is used. (Unit: meters)

- Default value: 3
- Acceptable value range: From 0 to 32

==== Allow Mining Underground Minerals / [allow_mining_underground_minerals]
Specify whether or not to allow mining underground minerals.

- Default value: true

==== Need To Wishbone For Mining Underground Minerals / [need_to_equip_wishbone_for_mining_underground_minerals]
Specify whether or not to require a wishbone to mine underground minerals.

- Default value: true
