=== [ #1 Logging ] / [logging]
==== Logging / [logging_enabled]
Enable logging. Regardless of the value set here, the log of Automatics initialization process will always be output.

- Default value: false

==== Allowed Log Level / [allowed_log_level]
Specifies the level at which logging is allowed.

- Default value: Fatal, Error, Warning, Message
- Acceptable values: None, Fatal, Error, Warning, Message, Info, Debug, All
- Multiple values can be set at the same time by separating them with , (e.g. Fatal, Error)

=== [ #2 Automatic Door ] / [automatic_door]
==== Automatic Door / [automatic_door_enabled]
Enable the function to open and close the door automatically.

- Default value: true

==== Allow Automatic Door / [allow_automatic_door]
Specify which doors are allowed to open and close automatically.

- Default value: All
- Acceptable values: None, WoodDoor, WoodGate, IronGate, DarkwoodGate, WoodShutter, All
- Multiple values can be set at the same time by separating them with , (e.g. WoodDoor, WoodGate)

==== Allow Automatic Door (Custom) / [allow_automatic_door_custom]
Specify the display or internal name of any door that is allowed to open and close automatically. A display name is a name displayed in the game, such as "Wood door", and the specified value will enable the automatic door if it partially matches the target display name. The internal name is the name used on the program side, such as "$piece_wooddoor", and the specified value must exactly match the target's internal name for the automatic door to be enabled.

- Default value:

==== Interval To Open / [interval_to_open]
the interval at which to call the process to determine whether to open the door. (Unit: second)

- Default value: 0.1
- Acceptable value range: From 0.1 to 8

==== Interval To Close / [interval_to_close]
the interval at which to call the process to determine whether to close the door. (Unit: second)

- Default value: 0.1
- Acceptable value range: From 0.1 to 8

==== Player Search Radius To Open / [player_search_radius_to_open]
The door automatically open when the player is inside the specified radius, with the door as the origin. (Unit: meter)

- Default value: 2.5
- Acceptable value range: From 1 to 8

==== Player Search Radius To Close / [player_search_radius_to_close]
The door automatically close when the player is inside the specified radius, with the door as the origin. (Unit: meter)

- Default value: 2.5
- Acceptable value range: From 1 to 8

==== Toggle Automatic Door Enabled / [toggle_automatic_door_enabled_key]
Shortcut key to enable/disable the automatic door.

- Default value:

=== [ #3 Automatic Map Pinning ] / [automatic_map_pinning]
==== Automatic Map Pinning / [automatic_map_pinning_enabled]
Enables automatic pinning to the map.

- Default value: true

==== Dynamic Object Search Range / [dynamic_object_search_range]
Specify the range of dynamic objects to be explored. "Dynamic Object" are objects that change position, such as animals, monsters, etc. Set to 0 to disable pinning of dynamic objects. (Unit: meter)

- Default value: 64
- Acceptable value range: From 0 to 256

==== Static Object Search Range / [static_object_search_range]
Specify the range of static objects to be explored. "Static Object" are objects that do not change their position, such as plants, veins, etc. Setting this to 0 disables pinning of static objects. (Unit: meter)

- Default value: 16
- Acceptable value range: From 0 to 256

==== Location Search Range / [location_search_range]
Specify the range of location to be explored. "Location" is a specific place, such as dungeon, fuling village, etc. Setting this to 0 disables location pinning. (Unit: meter)

- Default value: 96
- Acceptable value range: From 0 to 256

==== Allow Pinning Animal / [allow_pinning_animal]
Specify the animals to be automatic pinning.

- Default value: All
- Acceptable values: None, Boar, Deer, Wolf, Lox, Bird, Fish, All
- Multiple values can be set at the same time by separating them with , (e.g. Boar, Deer)

==== Allow Pinning Monster / [allow_pinning_monster]
Specify the monsters to be automatic pinning.

- Default value: All
- Acceptable values: None, Greyling, Neck, Ghost, Greydwarf, GreydwarfBrute, GreydwarfShaman, RancidRemains, Skeleton, Troll, Abomination, Blob, Draugr, DraugrElite, Leech, Oozer, Surtling, Wraith, Drake, Fenring, StoneGolem, Deathsquito, Fuling, FulingBerserker, FulingShaman, Growth, Serpent, Bat, FenringCultist, Ulv, All
- Multiple values can be set at the same time by separating them with , (e.g. Greyling, Neck)

==== Allow Pinning Flora / [allow_pinning_flora]
Specify the flora to be automatic pinning.

- Default value: Mushroom, Raspberries, Blueberries, CarrotSeeds, Thistle, TurnipSeeds, Cloudberries
- Acceptable values: None, Dandelion, Mushroom, Raspberries, Blueberries, Carrot, CarrotSeeds, YellowMushroom, Thistle, Turnip, TurnipSeeds, Onion, OnionSeeds, Barley, Cloudberries, Flex, All
- Multiple values can be set at the same time by separating them with , (e.g. Dandelion, Mushroom)

==== Allow Pinning Vein / [allow_pinning_vein]
Specify the veins to be automatic pinning.

- Default value: -9
- Acceptable values: None, Copper, Tin, MudPile, Obsidian, Silver, All
- Multiple values can be set at the same time by separating them with , (e.g. Copper, Tin)

==== Allow Pinning Spawner / [allow_pinning_spawner]
Specify the spawners to be automatic pinning.

- Default value: None
- Acceptable values: None, GreydwarfNest, EvilBonePile, BodyPile, All
- Multiple values can be set at the same time by separating them with , (e.g. GreydwarfNest, EvilBonePile)

==== Allow Pinning Other Object / [allow_pinning_other]
Specify the other objects to be automatic pinning.

- Default value: WildBeehive
- Acceptable values: None, Vegvisir, Runestone, WildBeehive, Portal, All
- Multiple values can be set at the same time by separating them with , (e.g. Vegvisir, Runestone)

==== Allow Pinning Dungeon / [allow_pinning_dungeon]
Specify the dungeons to be automatic pinning.

- Default value: All
- Acceptable values: None, BurialChambers, TrollCave, SunkenCrypts, MountainCave, All
- Multiple values can be set at the same time by separating them with , (e.g. BurialChambers, TrollCave)

==== Allow Pinning Spot / [allow_pinning_spot]
Specify the spots to be automatic pinning.

- Default value: All
- Acceptable values: None, InfestedTree, FireHole, DrakeNest, GoblinCamp, TarPit, All
- Multiple values can be set at the same time by separating them with , (e.g. InfestedTree, FireHole)

==== Allow Pinning Ship / [allow_pinning_ship]
Enable automatic pinning for the ship.

- Default value: true

==== Allow Pinning Animal (Custom) / [allow_pinning_animal_custom]
Specify the display or internal name of any animals that is allowed to automatic map pinning. A display name is the name displayed in the game, such as "Boar", and the specified value will enable the pinning if it partially matches the target display name. Internal name is the name used on the program side, such as "$enemy_boar", and the specified value must exactly match the target's internal name for the pinning to be enabled.

- Default value:

==== Allow Pinning Monster (Custom) / [allow_pinning_monster_custom]
Specify the display or internal name of any monster that is allowed to automatic map pinning. A display name is the name displayed in the game, such as "Greyling", and the specified value will enable the pinning if it partially matches the target display name. Internal name is the name used on the program side, such as "$enemy_greyling", and the specified value must exactly match the target's internal name for the pinning to be enabled.

- Default value:

==== Allow Pinning Flora (Custom) / [allow_pinning_flora_custom]
Specify the display or internal name of any flora that is allowed to automatic map pinning. A display name is the name displayed in the game, such as "Dandelion", and the specified value will enable the pinning if it partially matches the target display name. Internal name is the name used on the program side, such as "$item_dandelion", and the specified value must exactly match the target's internal name for the pinning to be enabled.

- Default value:

==== Allow Pinning Vein (Custom) / [allow_pinning_vein_custom]
Specify the display or internal name of any veins that is allowed to automatic map pinning. A display name is the name displayed in the game, such as "Copper deposit", and the specified value will enable the pinning if it partially matches the target display name. Internal name is the name used on the program side, such as "$piece_deposit_copper", and the specified value must exactly match the target's internal name for the pinning to be enabled.

- Default value:

==== Allow Pinning Spawner (Custom) / [allow_pinning_spawner_custom]
Specify the display or internal name of any spawners that is allowed to automatic map pinning. A display name is the name displayed in the game, such as "Greydwarf nest", and the specified value will enable the pinning if it partially matches the target display name. Internal name is the name used on the program side, such as "$enemy_greydwarfspawner", and the specified value must exactly match the target's internal name for the pinning to be enabled.

- Default value:

==== Not Pinning Tamed Animals / [ignore_tamed_animals]
Exclude tamed animals from automatic pinning.

- Default value: true

==== Static Object Search Interval / [static_object_search_interval]
Specify the interval at which static object search. Setting to 0 disables periodic static object search. (Unit: second)

- Default value: 0.25
- Acceptable value range: From 0 to 8

==== Flora Pins Merge Range / [flora_pins_merge_range]
When pinning flora, it recursively searches for the same flora that exist within a specified range and merge them into a single pin. (Unit: meter)

- Default value: 8
- Acceptable value range: From 0 to 16

==== In Ground Veins Need Wishbone / [in_ground_veins_need_wishbone]
Specify whether need to equip a Wishbone to pinning a vein that in ground.

- Default value: true

==== Static Object Search / [static_object_search_key]
Specify shortcut keys for searching static objects. Setting this item disables the static object search at regular intervals, so that it is performed only once each time the shortcut key is pressed.

- Default value:

=== [ #4 Automatic Processing ] / [automatic_processing]
==== Automatic Processing / [automatic_processing_enabled]
Enable automatic functions for tasks such as cooking, refining, and refilling fuel.

- Default value: true

==== Beehive Allow Processing / [piece_beehive_allow_automatic_processing]
Specify the automatic processing to be allowed for Beehive

- Default value: Store
- Acceptable values: None, Store

==== Beehive Container Search Range / [piece_beehive_container_search_range]
Specify the maximum distance which Beehive will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Products To Suppress Automatic Processing For Beehive / [piece_beehive_product_count_that_suppress_automatic_store]
Suppresses automatic processing of Beehive to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Bonfire Allow Processing / [piece_bonfire_allow_automatic_processing]
Specify the automatic processing to be allowed for Bonfire

- Default value: Refuel
- Acceptable values: None, Refuel

==== Bonfire Container Search Range / [piece_bonfire_container_search_range]
Specify the maximum distance which Bonfire will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Fuels To Suppress Automatic Processing For Bonfire / [piece_bonfire_fuel_count_that_suppress_automatic_process]
Suppresses automatic processing of Bonfire to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Blast furnace Allow Processing / [piece_blastfurnace_allow_automatic_processing]
Specify the automatic processing to be allowed for Blast furnace

- Default value: Craft, Refuel, Store
- Acceptable values: None, Craft, Refuel, StoreMultiple values can be set at the same time by separating them with , (e.g. Craft, Refuel)

==== Blast furnace Container Search Range / [piece_blastfurnace_container_search_range]
Specify the maximum distance which Blast furnace will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Materials To Suppress Automatic Processing For Blast furnace / [piece_blastfurnace_material_count_that_suppress_automatic_process]
Suppresses automatic processing of Blast furnace to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Count Of Fuels To Suppress Automatic Processing For Blast furnace / [piece_blastfurnace_fuel_count_that_suppress_automatic_process]
Suppresses automatic processing of Blast furnace to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Count Of Products To Suppress Automatic Processing For Blast furnace / [piece_blastfurnace_product_count_that_suppress_automatic_store]
Suppresses automatic processing of Blast furnace to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Refuel Blast furnace Only When Materials Supplied / [piece_blastfurnace_refuel_only_when_materials_supplied]
Performs automatic refuel only when materials are supplied to Blast furnace.

- Default value: false

==== Campfire Allow Processing / [piece_firepit_allow_automatic_processing]
Specify the automatic processing to be allowed for Campfire

- Default value: Refuel
- Acceptable values: None, Refuel

==== Campfire Container Search Range / [piece_firepit_container_search_range]
Specify the maximum distance which Campfire will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Fuels To Suppress Automatic Processing For Campfire / [piece_firepit_fuel_count_that_suppress_automatic_process]
Suppresses automatic processing of Campfire to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Charcoal kiln Allow Processing / [piece_charcoalkiln_allow_automatic_processing]
Specify the automatic processing to be allowed for Charcoal kiln

- Default value: Craft, Store
- Acceptable values: None, Craft, StoreMultiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Charcoal kiln Container Search Range / [piece_charcoalkiln_container_search_range]
Specify the maximum distance which Charcoal kiln will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Materials To Suppress Automatic Processing For Charcoal kiln / [piece_charcoalkiln_material_count_that_suppress_automatic_process]
Suppresses automatic processing of Charcoal kiln to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Count Of Products To Suppress Automatic Processing For Charcoal kiln / [piece_charcoalkiln_product_count_that_suppress_automatic_store]
Suppresses automatic processing of Charcoal kiln to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Cooking station Allow Processing / [piece_cookingstation_allow_automatic_processing]
Specify the automatic processing to be allowed for Cooking station

- Default value: Store
- Acceptable values: None, Craft, StoreMultiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Cooking station Container Search Range / [piece_cookingstation_container_search_range]
Specify the maximum distance which Cooking station will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Materials To Suppress Automatic Processing For Cooking station / [piece_cookingstation_material_count_that_suppress_automatic_process]
Suppresses automatic processing of Cooking station to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Count Of Products To Suppress Automatic Processing For Cooking station / [piece_cookingstation_product_count_that_suppress_automatic_store]
Suppresses automatic processing of Cooking station to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Fermenter Allow Processing / [piece_fermenter_allow_automatic_processing]
Specify the automatic processing to be allowed for Fermenter

- Default value: Craft, Store
- Acceptable values: None, Craft, StoreMultiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Fermenter Container Search Range / [piece_fermenter_container_search_range]
Specify the maximum distance which Fermenter will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Materials To Suppress Automatic Processing For Fermenter / [piece_fermenter_material_count_that_suppress_automatic_process]
Suppresses automatic processing of Fermenter to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Count Of Products To Suppress Automatic Processing For Fermenter / [piece_fermenter_product_count_that_suppress_automatic_store]
Suppresses automatic processing of Fermenter to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Hanging brazier Allow Processing / [piece_brazierceiling01_allow_automatic_processing]
Specify the automatic processing to be allowed for Hanging brazier

- Default value: Refuel
- Acceptable values: None, Refuel

==== Hanging brazier Container Search Range / [piece_brazierceiling01_container_search_range]
Specify the maximum distance which Hanging brazier will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Fuels To Suppress Automatic Processing For Hanging brazier / [piece_brazierceiling01_fuel_count_that_suppress_automatic_process]
Suppresses automatic processing of Hanging brazier to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Hearth Allow Processing / [piece_hearth_allow_automatic_processing]
Specify the automatic processing to be allowed for Hearth

- Default value: Refuel
- Acceptable values: None, Refuel

==== Hearth Container Search Range / [piece_hearth_container_search_range]
Specify the maximum distance which Hearth will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Fuels To Suppress Automatic Processing For Hearth / [piece_hearth_fuel_count_that_suppress_automatic_process]
Suppresses automatic processing of Hearth to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Iron cooking station Allow Processing / [piece_cookingstation_iron_allow_automatic_processing]
Specify the automatic processing to be allowed for Iron cooking station

- Default value: Store
- Acceptable values: None, Craft, StoreMultiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Iron cooking station Container Search Range / [piece_cookingstation_iron_container_search_range]
Specify the maximum distance which Iron cooking station will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Materials To Suppress Automatic Processing For Iron cooking station / [piece_cookingstation_iron_material_count_that_suppress_automatic_process]
Suppresses automatic processing of Iron cooking station to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Count Of Products To Suppress Automatic Processing For Iron cooking station / [piece_cookingstation_iron_product_count_that_suppress_automatic_store]
Suppresses automatic processing of Iron cooking station to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Jack-o-turnip Allow Processing / [piece_jackoturnip_allow_automatic_processing]
Specify the automatic processing to be allowed for Jack-o-turnip

- Default value: Refuel
- Acceptable values: None, Refuel

==== Jack-o-turnip Container Search Range / [piece_jackoturnip_container_search_range]
Specify the maximum distance which Jack-o-turnip will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Fuels To Suppress Automatic Processing For Jack-o-turnip / [piece_jackoturnip_fuel_count_that_suppress_automatic_process]
Suppresses automatic processing of Jack-o-turnip to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Sconce Allow Processing / [piece_sconce_allow_automatic_processing]
Specify the automatic processing to be allowed for Sconce

- Default value: Refuel
- Acceptable values: None, Refuel

==== Sconce Container Search Range / [piece_sconce_container_search_range]
Specify the maximum distance which Sconce will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Fuels To Suppress Automatic Processing For Sconce / [piece_sconce_fuel_count_that_suppress_automatic_process]
Suppresses automatic processing of Sconce to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Smelter Allow Processing / [piece_smelter_allow_automatic_processing]
Specify the automatic processing to be allowed for Smelter

- Default value: Craft, Refuel, Store
- Acceptable values: None, Craft, Refuel, StoreMultiple values can be set at the same time by separating them with , (e.g. Craft, Refuel)

==== Smelter Container Search Range / [piece_smelter_container_search_range]
Specify the maximum distance which Smelter will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Materials To Suppress Automatic Processing For Smelter / [piece_smelter_material_count_that_suppress_automatic_process]
Suppresses automatic processing of Smelter to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Count Of Fuels To Suppress Automatic Processing For Smelter / [piece_smelter_fuel_count_that_suppress_automatic_process]
Suppresses automatic processing of Smelter to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Count Of Products To Suppress Automatic Processing For Smelter / [piece_smelter_product_count_that_suppress_automatic_store]
Suppresses automatic processing of Smelter to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Refuel Smelter Only When Materials Supplied / [piece_smelter_refuel_only_when_materials_supplied]
Performs automatic refuel only when materials are supplied to Smelter.

- Default value: false

==== Spinning wheel Allow Processing / [piece_spinningwheel_allow_automatic_processing]
Specify the automatic processing to be allowed for Spinning wheel

- Default value: Store
- Acceptable values: None, Craft, StoreMultiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Spinning wheel Container Search Range / [piece_spinningwheel_container_search_range]
Specify the maximum distance which Spinning wheel will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Materials To Suppress Automatic Processing For Spinning wheel / [piece_spinningwheel_material_count_that_suppress_automatic_process]
Suppresses automatic processing of Spinning wheel to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Count Of Products To Suppress Automatic Processing For Spinning wheel / [piece_spinningwheel_product_count_that_suppress_automatic_store]
Suppresses automatic processing of Spinning wheel to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Standing blue-burning iron torch Allow Processing / [piece_groundtorchblue_allow_automatic_processing]
Specify the automatic processing to be allowed for Standing blue-burning iron torch

- Default value: Refuel
- Acceptable values: None, Refuel

==== Standing blue-burning iron torch Container Search Range / [piece_groundtorchblue_container_search_range]
Specify the maximum distance which Standing blue-burning iron torch will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Fuels To Suppress Automatic Processing For Standing blue-burning iron torch / [piece_groundtorchblue_fuel_count_that_suppress_automatic_process]
Suppresses automatic processing of Standing blue-burning iron torch to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Standing brazier Allow Processing / [piece_brazierfloor01_allow_automatic_processing]
Specify the automatic processing to be allowed for Standing brazier

- Default value: Refuel
- Acceptable values: None, Refuel

==== Standing brazier Container Search Range / [piece_brazierfloor01_container_search_range]
Specify the maximum distance which Standing brazier will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Fuels To Suppress Automatic Processing For Standing brazier / [piece_brazierfloor01_fuel_count_that_suppress_automatic_process]
Suppresses automatic processing of Standing brazier to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Standing green-burning iron torch Allow Processing / [piece_groundtorchgreen_allow_automatic_processing]
Specify the automatic processing to be allowed for Standing green-burning iron torch

- Default value: Refuel
- Acceptable values: None, Refuel

==== Standing green-burning iron torch Container Search Range / [piece_groundtorchgreen_container_search_range]
Specify the maximum distance which Standing green-burning iron torch will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Fuels To Suppress Automatic Processing For Standing green-burning iron torch / [piece_groundtorchgreen_fuel_count_that_suppress_automatic_process]
Suppresses automatic processing of Standing green-burning iron torch to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Standing iron torch Allow Processing / [piece_groundtorch_allow_automatic_processing]
Specify the automatic processing to be allowed for Standing iron torch

- Default value: Refuel
- Acceptable values: None, Refuel

==== Standing iron torch Container Search Range / [piece_groundtorch_container_search_range]
Specify the maximum distance which Standing iron torch will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Fuels To Suppress Automatic Processing For Standing iron torch / [piece_groundtorch_fuel_count_that_suppress_automatic_process]
Suppresses automatic processing of Standing iron torch to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Standing wood torch Allow Processing / [piece_groundtorchwood_allow_automatic_processing]
Specify the automatic processing to be allowed for Standing wood torch

- Default value: Refuel
- Acceptable values: None, Refuel

==== Standing wood torch Container Search Range / [piece_groundtorchwood_container_search_range]
Specify the maximum distance which Standing wood torch will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Fuels To Suppress Automatic Processing For Standing wood torch / [piece_groundtorchwood_fuel_count_that_suppress_automatic_process]
Suppresses automatic processing of Standing wood torch to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Stone oven Allow Processing / [piece_oven_allow_automatic_processing]
Specify the automatic processing to be allowed for Stone oven

- Default value: Craft, Refuel, Store
- Acceptable values: None, Craft, Refuel, Store
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Refuel)

==== Stone oven Container Search Range / [piece_oven_container_search_range]
Specify the maximum distance which Stone oven will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Materials To Suppress Automatic Processing For Stone oven / [piece_oven_material_count_that_suppress_automatic_process]
Suppresses automatic processing of Stone oven to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Count Of Fuels To Suppress Automatic Processing For Stone oven / [piece_oven_fuel_count_that_suppress_automatic_process]
Suppresses automatic processing of Stone oven to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Count Of Products To Suppress Automatic Processing For Stone oven / [piece_oven_product_count_that_suppress_automatic_store]
Suppresses automatic processing of Stone oven to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

==== Refuel Stone oven Only When Materials Supplied / [piece_oven_refuel_only_when_materials_supplied]
Performs automatic refuel only when materials are supplied to Stone oven.

- Default value: false

==== Windmill Allow Processing / [piece_windmill_allow_automatic_processing]
Specify the automatic processing to be allowed for Windmill

- Default value: Store
- Acceptable values: None, Craft, StoreMultiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Windmill Container Search Range / [piece_windmill_container_search_range]
Specify the maximum distance which Windmill will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Count Of Materials To Suppress Automatic Processing For Windmill / [piece_windmill_material_count_that_suppress_automatic_process]
Suppresses automatic processing of Windmill to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 9999

==== Count Of Products To Suppress Automatic Processing For Windmill / [piece_windmill_product_count_that_suppress_automatic_store]
Suppresses automatic processing of Windmill to prevent the count of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 9999

=== [ #5 Automatic Feeding ] / [automatic_feeding]
==== Automatic Feeding / [automatic_feeding_enabled]
Enable automatic feeding for animals.

- Default value: true

==== Feed Search Range / [feed_search_range]
Specify the maximum distance which animal will search for food. 0 disables the feed box search and -1 uses the default value for each animal. (Unit: meter)

- Default value: -1
- Acceptable value range: From -1 to 64

==== Need Close To Eat The Feed / [need_close_to_eat_the_feed]
Specify whether or not the animal needs to approach the food in order to eat it.

- Default value: false

==== Allow To Feed From Container / [allow_to_feed_from_container]
Specify the types of animals allowed to feed from the container.

- Default value: Tamed
- Acceptable values: None, Wild, Tamed, All
- Multiple values can be set at the same time by separating them with , (e.g. Wild, Tamed)

=== [ #6 Automatic Repair ] / [automatic_repair]
==== Automatic Repair / [automatic_repair_enabled]
Enable automatic repair of items and pieces.

- Default value: true

==== Crafting Station Search Range / [crafting_station_search_range]
Specify the range to search for a crafting station to be used to repair items. Setting to 0 disables periodic item repair. (Unit: meters)

- Default value: 16
- Acceptable value range: From 0 to 64

==== Repair Items When Accessing The Crafting Station / [repair_items_when_accessing_the_crafting_station]
Specify whether or not to repair all items that can be repaired when the workbench GUI is opened.

- Default value: false

==== Item Repair Message / [item_repair_message]
Specify where the message is displayed when an item is repaired.

- Default value: None
- Acceptable values: None, Center, TopLeft

==== Piece Search Range / [piece_search_range]
Specify the range to search for a pieces to repair. Setting to 0 disables periodic pieces repairs. (Unit: meters)

- Default value: 16
- Acceptable value range: From 0 to 64

==== Piece Repair Message / [piece_repair_message]
Specify where the message is displayed when a piece is repaired.

- Default value: None
- Acceptable values: None, Center, TopLeft
