=== [ #1 System ] / [system]
==== Logging / [enable_logging]
Specify whether to enable log output. System initialization logs for Automatics are always output regardless of the value of this option.

- Default value: false

==== Log Level To Allow Logging / [log_level_to_allow_logging]
Specify the log level that allows logging.

- Default value: Fatal, Error, Warning, Message
- Acceptable values: None, Fatal, Error, Warning, Message, Info, Debug, All
- Multiple values can be set at the same time by separating them with , (e.g. Fatal, Error)

==== [Deprecated] Resources Directory / [resources_directory]
[This option will be discontinued in the near future. Check the README for details]

- Default value:

=== [ #2 General ] / [general]
==== User-defined Animal / [custom_animal]
Any animal can be added. Identifier: a unique string that does not overlap with any other identifier. White spaces are not allowed. Label: The name of the animal. Mainly used in GUI. If you specify an internal name, it will be translated automatically. Pattern: A pattern matching the internal name of the animal. Exact matches are evaluated. You can set a regular expression by concatenating r/ at the beginning.

- Default value:

==== User-defined Dungeon / [custom_dungeon]
Any dungeon can be added. Identifier: a unique string that does not overlap with any other identifier. White spaces are not allowed. Label: The name of the dungeon. Mainly used in GUI. If you specify an internal name, it will be translated automatically. Pattern: A pattern matching the prefab name of the dungeon. Exact matches are evaluated. You can set a regular expression by concatenating r/ at the beginning.

- Default value:

==== User-defined Flora / [custom_flora]
Any flora can be added. Identifier: a unique string that does not overlap with any other identifier. White spaces are not allowed. Label: The name of the flora. Mainly used in GUI. If you specify an internal name, it will be translated automatically. Pattern: A pattern matching the internal name of the flora. Exact matches are evaluated. You can set a regular expression by concatenating r/ at the beginning.

- Default value:

==== User-defined Mineral / [custom_mineral]
Any mineral can be added. Identifier: a unique string that does not overlap with any other identifier. White spaces are not allowed. Label: The name of the mineral. Mainly used in GUI. If you specify an internal name, it will be translated automatically. Pattern: A pattern matching the internal name of the mineral. Exact matches are evaluated. You can set a regular expression by concatenating r/ at the beginning.

- Default value:

==== User-defined Monster / [custom_monster]
Any monster can be added. Identifier: a unique string that does not overlap with any other identifier. White spaces are not allowed. Label: The name of the monster. Mainly used in GUI. If you specify an internal name, it will be translated automatically. Pattern: A pattern matching the internal name of the monster. Exact matches are evaluated. You can set a regular expression by concatenating r/ at the beginning.

- Default value:

==== User-defined Spawner / [custom_spawner]
Any spawner can be added. Identifier: a unique string that does not overlap with any other identifier. White spaces are not allowed. Label: The name of the spawner. Mainly used in GUI. If you specify an internal name, it will be translated automatically. Pattern: A pattern matching the internal name of the spawner. Exact matches are evaluated. You can set a regular expression by concatenating r/ at the beginning.

- Default value:

==== User-defined Spot / [custom_spot]
Any spot can be added. Identifier: a unique string that does not overlap with any other identifier. White spaces are not allowed. Label: The name of the spot. Mainly used in GUI. If you specify an internal name, it will be translated automatically. Pattern: A pattern matching the prefab name of the spot. Exact matches are evaluated. You can set a regular expression by concatenating r/ at the beginning.

- Default value:

==== User-defined Door / [custom_door]
Any door can be added. Identifier: a unique string that does not overlap with any other identifier. White spaces are not allowed. Label: The name of the door. Mainly used in GUI. If you specify an internal name, it will be translated automatically. Pattern: A pattern matching the internal name of the door. Exact matches are evaluated. You can set a regular expression by concatenating r/ at the beginning.

- Default value:

==== User-defined Vehicle / [custom_vehicle]
Any vehicle can be added. Identifier: a unique string that does not overlap with any other identifier. White spaces are not allowed. Label: The name of the vehicle. Mainly used in GUI. If you specify an internal name, it will be translated automatically. Pattern: A pattern matching the prefab name of the vehicle. Exact matches are evaluated. You can set a regular expression by concatenating r/ at the beginning.

- Default value:

==== User-defined Other Object / [custom_other]
Any object can be added. Identifier: a unique string that does not overlap with any other identifier. White spaces are not allowed. Label: The name of the object. Mainly used in GUI. If you specify an internal name, it will be translated automatically. Pattern: A pattern matching the internal or prefab name of the object. Exact matches are evaluated. You can set a regular expression by concatenating r/ at the beginning.

- Default value:

=== [ #3 Automatic Door ] / [automatic_door]
==== Disable Module / [disable_module]
You can disable this feature completely to avoid adding logic you don't need. (Game must be restart for reflect this option)

- Default value: false

==== Automatic Door / [enable_automatic_door]
Specify whether to enable the feature that automatically opens and closes the door.

- Default value: true

==== Allow Automatic Door / [allow_automatic_door]
Specify which doors are allowed to open and close automatically.

- Default value: WoodDoor, WoodGate, IronGate, DarkwoodGate

==== Interval To Open / [interval_to_open]
Specify the interval at which the process of automatically opening the door is called. If set to less than 0.1, the function to automatically open the door will be disabled. (Unit: second)

- Default value: 0.1
- Acceptable value range: From 0 to 8

==== Interval To Close / [interval_to_close]
Specify the interval at which the process of automatically closing the door is called. If set to less than 0.1, the function to automatically close the door will be disabled. (Unit: second)

- Default value: 0.1
- Acceptable value range: From 0 to 8

==== Distance For Automatic Opening / [distance_for_automatic_opening]
Specify how close the player must be to the door in order for it to open automatically. (Unit: meter)

- Default value: 2.5
- Acceptable value range: From 1 to 8

==== Distance For Automatic Closing / [distance_for_automatic_closing]
Specify how far the player must be from the door for the door to close automatically. (Unit: meter)

- Default value: 2.5
- Acceptable value range: From 1 to 8

==== Automatic Door Enable/Disable Toggle Message / [automatic_door_enable_disable_toggle_message]
Specify where a message is displayed when the automatic door is enabled or disabled by a shortcut key.

- Default value: Center
- Acceptable values: None, Center, TopLeft

==== Automatic Door Enable/Disable Toggle / [automatic_door_enable_disable_toggle]
Specify a shortcut key to enable/disable the automatic door.

- Default value:

=== [ #4 Automatic Mapping ] / [automatic_mapping]
==== Disable Module / [module_disable]
You can disable this feature completely to avoid adding logic you don't need. (Game must be restart for reflect this option)

- Default value: false

==== Automatic Mapping / [enable_automatic_mapping]
Specify whether to enable the feature that automatically pinning objects and locations to the map.

- Default value: true

==== Dynamic Object Search Range / [dynamic_object_mapping_range]
Specify the range of dynamic objects to be explored. "Dynamic Object" are objects that change position, such as animals, monsters, etc. Set to 0 to disable pinning of dynamic objects. (Unit: meter)

- Default value: 64
- Acceptable value range: From 0 to 128

==== Static Object Search Range / [static_object_mapping_range]
Specify the range of static objects to be explored. "Static Object" are objects that do not change their position, such as flora, mineral, etc. Setting this to 0 disables pinning of static objects. (Unit: meter)

- Default value: 32
- Acceptable value range: From 0 to 128

==== Location Search Range / [location_mapping_range]
Specify the range of location to be explored. "Location" is a specific place, such as dungeon, fuling village, etc. Setting this to 0 disables location pinning. (Unit: meter)

- Default value: 96
- Acceptable value range: From 0 to 128

==== Allow Pinning Animal / [allow_pinning_animal]
Specify the animals to be automatic pinning.

- Default value: Boar, Piggy, Deer, Wolf, WolfCub, Lox, LoxCalf, Hen, Chicken, Hare, Bird, Fish

==== Allow Pinning Monster / [allow_pinning_monster]
Specify the monsters to be automatic pinning.

- Default value: Greyling, Neck, Ghost, Greydwarf, GreydwarfBrute, GreydwarfShaman, RancidRemains, Skeleton, Troll, Abomination, Blob, Draugr, DraugrElite, Leech, Oozer, Surtling, Wraith, Drake, Fenring, StoneGolem, Deathsquito, Fuling, FulingBerserker, FulingShaman, Growth, Serpent, Bat, FenringCultist, Ulv, DvergrRogue, DvergrMage, Tick, Seeker, SeekerBrood, Gjall, SeekerSoldier

==== Allow Pinning Flora / [allow_pinning_flora]
Specify the flora to be automatic pinning.

- Default value: Mushroom, Raspberries, Blueberries, CarrotSeeds, Thistle, TurnipSeeds, Cloudberries, JotunPuffs, Magecap

==== Allow Pinning Mineral / [allow_pinning_mineral]
Specify the mineral to be automatic pinning.

- Default value: CopperDeposit, TinDeposit, MudPile, SilverVein, PetrifiedBone, SoftTissue

==== Allow Pinning Spawner / [allow_pinning_spawner]
Specify the spawners to be automatic pinning.

- Default value:

==== Allow Pinning Vehicle / [allow_pinning_vehicle]
Specify the vehicles to be automatic pinning.

- Default value: Karve, Longship

==== Allow Pinning Other Object / [allow_pinning_other]
Specify the other objects to be automatic pinning.

- Default value: WildBeehive

==== Allow Pinning Dungeon / [allow_pinning_dungeon]
Specify the dungeons to be automatic pinning.

- Default value: BurialChambers, TrollCave, SunkenCrypts, MountainCave, InfestedMine

==== Allow Pinning Spot / [allow_pinning_spot]
Specify the spots to be automatic pinning.

- Default value: InfestedTree, FireHole, DrakeNest, GoblinCamp, TarPit, DvergrExcavation, DvergrGuardTower, DvergrHarbour, DvergrLighthouse, PetrifiedBone

==== Allow Pinning Portal / [allow_pinning_portal]
Enable automatic pinning for the portal. Portal is treated as a static object.

- Default value: true

==== Not Pinning Tamed Animals / [not_pinning_tamed_animals]
Exclude tamed animals from automatic pinning.

- Default value: true

==== Static Object Mapping Interval / [static_object_mapping_interval]
Specify the interval at which static object mapping. Setting to 0 disables periodic static object mapping. (Unit: second)

- Default value: 0.25
- Acceptable value range: From 0 to 4

==== Static Object Caching Interval / [static_object_caching_interval]
Specify the interval at which static objects will be cached. Mapping of static objects uses this cache. (Unit: second)

- Default value: 3
- Acceptable value range: From 1 to 8

==== Save Static Object Pins / [save_static_object_pins]
Specify whether to save the pins of static objects.

- Default value: false

==== Remove Pins Of Destroyed Object / [remove_pins_of_destroyed_object]
Specify whether or not to automatically remove pins of objects that have been destroyed and no longer exist.

- Default value: true

==== Flora Pins Merge Range / [flora_pins_merge_range]
When pinning flora, it recursively searches for the same flora that exist within a specified range and merge them into a single pin. (Unit: meter)

- Default value: 8
- Acceptable value range: From 0 to 16

==== Need To Equip Wishbone For Underground Minerals / [need_to_equip_wishbone_for_underground_minerals]
Specify whether the wishbone needs to be equipped to attempt to pinning underground minerals.

- Default value: true

==== Static Object Mapping / [static_object_mapping_key]
Specify shortcut keys for mapping static objects. Setting this item disables the static object mapping at regular intervals, so that it is performed only once each time the shortcut key is pressed.

- Default value:

=== [ #5 Automatic Processing ] / [automatic_processing]
==== Disable Module / [module_disable]
You can disable this feature completely to avoid adding logic you don't need. (Game must be restart for reflect this option)

- Default value: false

==== Automatic Processing / [enable_automatic_processing]
Specify whether to enable or disable the ability to automatically perform tasks such as cooking, refining, and refuel.

- Default value: true

==== Allow Processing By Beehive / [allow_processing_by_piece_beehive]
Specify the automatic processing to be allowed for Beehive

- Default value: Store
- Acceptable values: None, Store

==== Container Search Range By Beehive / [container_search_range_by_piece_beehive]
Specify the maximum distance which Beehive will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Allow Processing By Bonfire / [allow_processing_by_piece_bonfire]
Specify the automatic processing to be allowed for Bonfire

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Bonfire / [container_search_range_by_piece_bonfire]
Specify the maximum distance which Bonfire will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Bonfire / [piece_bonfire_fuel_count_of_suppress_processing]
Suppresses automatic processing of Bonfire to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Refuel Bonfire Only When Out Of Fuel / [piece_bonfire_refuel_only_when_out_of_fuel]
Performs automatic refuel only when Bonfire is out of fuel.

- Default value: false

==== Allow Processing By Blast furnace / [allow_processing_by_piece_blastfurnace]
Specify the automatic processing to be allowed for Blast furnace

- Default value: All
- Acceptable values: None, Craft, Refuel, Store, All
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Refuel)

==== Container Search Range By Blast furnace / [container_search_range_by_piece_blastfurnace]
Specify the maximum distance which Blast furnace will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Blast furnace / [piece_blastfurnace_material_count_of_suppress_processing]
Suppresses automatic processing of Blast furnace to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Product Stacks Of Suppress Processing For Blast furnace / [piece_blastfurnace_product_stacks_of_suppress_processing]
Suppresses automatic processing of Blast furnace to prevent the item stacks of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 99

==== Material Supply To Blast furnace Only When Materials Run Out / [piece_blastfurnace_supply_only_when_materials_run_out]
Performs automatic craft only when materials of Blast furnace run out.

- Default value: false

==== Fuel Count Of Suppress Processing For Blast furnace / [piece_blastfurnace_fuel_count_of_suppress_processing]
Suppresses automatic processing of Blast furnace to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Refuel Blast furnace Only When Out Of Fuel / [piece_blastfurnace_refuel_only_when_out_of_fuel]
Performs automatic refuel only when Blast furnace is out of fuel.

- Default value: false

==== Refuel Blast furnace Only When Materials Supplied / [piece_blastfurnace_refuel_only_when_materials_supplied]
Performs automatic refuel only when materials are supplied to Blast furnace.

- Default value: false

==== Allow Processing By Campfire / [allow_processing_by_piece_firepit]
Specify the automatic processing to be allowed for Campfire

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Campfire / [container_search_range_by_piece_firepit]
Specify the maximum distance which Campfire will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Campfire / [piece_firepit_fuel_count_of_suppress_processing]
Suppresses automatic processing of Campfire to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Refuel Campfire Only When Out Of Fuel / [piece_firepit_refuel_only_when_out_of_fuel]
Performs automatic refuel only when Campfire is out of fuel.

- Default value: false

==== Allow Processing By Charcoal kiln / [allow_processing_by_piece_charcoalkiln]
Specify the automatic processing to be allowed for Charcoal kiln

- Default value: Craft, Store
- Acceptable values: None, Craft, Store
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Container Search Range By Charcoal kiln / [container_search_range_by_piece_charcoalkiln]
Specify the maximum distance which Charcoal kiln will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Charcoal kiln / [piece_charcoalkiln_material_count_of_suppress_processing]
Suppresses automatic processing of Charcoal kiln to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Product Stacks Of Suppress Processing For Charcoal kiln / [piece_charcoalkiln_product_stacks_of_suppress_processing]
Suppresses automatic processing of Charcoal kiln to prevent the item stacks of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 99

==== Material Supply To Charcoal kiln Only When Materials Run Out / [piece_charcoalkiln_supply_only_when_materials_run_out]
Performs automatic craft only when materials of Charcoal kiln run out.

- Default value: false

==== Allow Processing By Cooking station / [allow_processing_by_piece_cookingstation]
Specify the automatic processing to be allowed for Cooking station

- Default value: Store
- Acceptable values: None, Craft, Store
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Container Search Range By Cooking station / [container_search_range_by_piece_cookingstation]
Specify the maximum distance which Cooking station will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Cooking station / [piece_cookingstation_material_count_of_suppress_processing]
Suppresses automatic processing of Cooking station to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Product Stacks Of Suppress Processing For Cooking station / [piece_cookingstation_product_stacks_of_suppress_processing]
Suppresses automatic processing of Cooking station to prevent the item stacks of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 99

==== Material Supply To Cooking station Only When Materials Run Out / [piece_cookingstation_supply_only_when_materials_run_out]
Performs automatic craft only when materials of Cooking station run out.

- Default value: false

==== Allow Processing By Fermenter / [allow_processing_by_piece_fermenter]
Specify the automatic processing to be allowed for Fermenter

- Default value: Craft, Store
- Acceptable values: None, Craft, Store
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Container Search Range By Fermenter / [container_search_range_by_piece_fermenter]
Specify the maximum distance which Fermenter will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Fermenter / [piece_fermenter_material_count_of_suppress_processing]
Suppresses automatic processing of Fermenter to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Product Stacks Of Suppress Processing For Fermenter / [piece_fermenter_product_stacks_of_suppress_processing]
Suppresses automatic processing of Fermenter to prevent the item stacks of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 99

==== Material Supply To Fermenter Only When Materials Run Out / [piece_fermenter_supply_only_when_materials_run_out]
Performs automatic craft only when materials of Fermenter run out.

- Default value: false

==== Allow Processing By Hanging brazier / [allow_processing_by_piece_brazierceiling01]
Specify the automatic processing to be allowed for Hanging brazier

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Hanging brazier / [container_search_range_by_piece_brazierceiling01]
Specify the maximum distance which Hanging brazier will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Hanging brazier / [piece_brazierceiling01_fuel_count_of_suppress_processing]
Suppresses automatic processing of Hanging brazier to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Refuel Hanging brazier Only When Out Of Fuel / [piece_brazierceiling01_refuel_only_when_out_of_fuel]
Performs automatic refuel only when Hanging brazier is out of fuel.

- Default value: false

==== Allow Processing By Hearth / [allow_processing_by_piece_hearth]
Specify the automatic processing to be allowed for Hearth

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Hearth / [container_search_range_by_piece_hearth]
Specify the maximum distance which Hearth will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Hearth / [piece_hearth_fuel_count_of_suppress_processing]
Suppresses automatic processing of Hearth to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Refuel Hearth Only When Out Of Fuel / [piece_hearth_refuel_only_when_out_of_fuel]
Performs automatic refuel only when Hearth is out of fuel.

- Default value: false

==== Allow Processing By Iron cooking station / [allow_processing_by_piece_cookingstation_iron]
Specify the automatic processing to be allowed for Iron cooking station

- Default value: Store
- Acceptable values: None, Craft, Store
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Container Search Range By Iron cooking station / [container_search_range_by_piece_cookingstation_iron]
Specify the maximum distance which Iron cooking station will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Iron cooking station / [piece_cookingstation_iron_material_count_of_suppress_processing]
Suppresses automatic processing of Iron cooking station to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Product Stacks Of Suppress Processing For Iron cooking station / [piece_cookingstation_iron_product_stacks_of_suppress_processing]
Suppresses automatic processing of Iron cooking station to prevent the item stacks of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 99

==== Material Supply To Iron cooking station Only When Materials Run Out / [piece_cookingstation_iron_supply_only_when_materials_run_out]
Performs automatic craft only when materials of Iron cooking station run out.

- Default value: false

==== Allow Processing By Jack-o-turnip / [allow_processing_by_piece_jackoturnip]
Specify the automatic processing to be allowed for Jack-o-turnip

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Jack-o-turnip / [container_search_range_by_piece_jackoturnip]
Specify the maximum distance which Jack-o-turnip will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Jack-o-turnip / [piece_jackoturnip_fuel_count_of_suppress_processing]
Suppresses automatic processing of Jack-o-turnip to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Refuel Jack-o-turnip Only When Out Of Fuel / [piece_jackoturnip_refuel_only_when_out_of_fuel]
Performs automatic refuel only when Jack-o-turnip is out of fuel.

- Default value: false

==== Allow Processing By Sconce / [allow_processing_by_piece_sconce]
Specify the automatic processing to be allowed for Sconce

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Sconce / [container_search_range_by_piece_sconce]
Specify the maximum distance which Sconce will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Sconce / [piece_sconce_fuel_count_of_suppress_processing]
Suppresses automatic processing of Sconce to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Refuel Sconce Only When Out Of Fuel / [piece_sconce_refuel_only_when_out_of_fuel]
Performs automatic refuel only when Sconce is out of fuel.

- Default value: false

==== Allow Processing By Smelter / [allow_processing_by_piece_smelter]
Specify the automatic processing to be allowed for Smelter

- Default value: All
- Acceptable values: None, Craft, Refuel, Store, All
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Refuel)

==== Container Search Range By Smelter / [container_search_range_by_piece_smelter]
Specify the maximum distance which Smelter will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Smelter / [piece_smelter_material_count_of_suppress_processing]
Suppresses automatic processing of Smelter to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Product Stacks Of Suppress Processing For Smelter / [piece_smelter_product_stacks_of_suppress_processing]
Suppresses automatic processing of Smelter to prevent the item stacks of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 99

==== Material Supply To Smelter Only When Materials Run Out / [piece_smelter_supply_only_when_materials_run_out]
Performs automatic craft only when materials of Smelter run out.

- Default value: false

==== Fuel Count Of Suppress Processing For Smelter / [piece_smelter_fuel_count_of_suppress_processing]
Suppresses automatic processing of Smelter to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Refuel Smelter Only When Out Of Fuel / [piece_smelter_refuel_only_when_out_of_fuel]
Performs automatic refuel only when Smelter is out of fuel.

- Default value: false

==== Refuel Smelter Only When Materials Supplied / [piece_smelter_refuel_only_when_materials_supplied]
Performs automatic refuel only when materials are supplied to Smelter.

- Default value: false

==== Allow Processing By Spinning wheel / [allow_processing_by_piece_spinningwheel]
Specify the automatic processing to be allowed for Spinning wheel

- Default value: Store
- Acceptable values: None, Craft, Store
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Container Search Range By Spinning wheel / [container_search_range_by_piece_spinningwheel]
Specify the maximum distance which Spinning wheel will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Spinning wheel / [piece_spinningwheel_material_count_of_suppress_processing]
Suppresses automatic processing of Spinning wheel to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Product Stacks Of Suppress Processing For Spinning wheel / [piece_spinningwheel_product_stacks_of_suppress_processing]
Suppresses automatic processing of Spinning wheel to prevent the item stacks of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 99

==== Material Supply To Spinning wheel Only When Materials Run Out / [piece_spinningwheel_supply_only_when_materials_run_out]
Performs automatic craft only when materials of Spinning wheel run out.

- Default value: false

==== Allow Processing By Standing blue-burning iron torch / [allow_processing_by_piece_groundtorchblue]
Specify the automatic processing to be allowed for Standing blue-burning iron torch

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Standing blue-burning iron torch / [container_search_range_by_piece_groundtorchblue]
Specify the maximum distance which Standing blue-burning iron torch will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Standing blue-burning iron torch / [piece_groundtorchblue_fuel_count_of_suppress_processing]
Suppresses automatic processing of Standing blue-burning iron torch to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Refuel Standing blue-burning iron torch Only When Out Of Fuel / [piece_groundtorchblue_refuel_only_when_out_of_fuel]
Performs automatic refuel only when Standing blue-burning iron torch is out of fuel.

- Default value: false

==== Allow Processing By Standing brazier / [allow_processing_by_piece_brazierfloor01]
Specify the automatic processing to be allowed for Standing brazier

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Standing brazier / [container_search_range_by_piece_brazierfloor01]
Specify the maximum distance which Standing brazier will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Standing brazier / [piece_brazierfloor01_fuel_count_of_suppress_processing]
Suppresses automatic processing of Standing brazier to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Refuel Standing brazier Only When Out Of Fuel / [piece_brazierfloor01_refuel_only_when_out_of_fuel]
Performs automatic refuel only when Standing brazier is out of fuel.

- Default value: false

==== Allow Processing By Standing green-burning iron torch / [allow_processing_by_piece_groundtorchgreen]
Specify the automatic processing to be allowed for Standing green-burning iron torch

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Standing green-burning iron torch / [container_search_range_by_piece_groundtorchgreen]
Specify the maximum distance which Standing green-burning iron torch will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Standing green-burning iron torch / [piece_groundtorchgreen_fuel_count_of_suppress_processing]
Suppresses automatic processing of Standing green-burning iron torch to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Refuel Standing green-burning iron torch Only When Out Of Fuel / [piece_groundtorchgreen_refuel_only_when_out_of_fuel]
Performs automatic refuel only when Standing green-burning iron torch is out of fuel.

- Default value: false

==== Allow Processing By Standing iron torch / [allow_processing_by_piece_groundtorch]
Specify the automatic processing to be allowed for Standing iron torch

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Standing iron torch / [container_search_range_by_piece_groundtorch]
Specify the maximum distance which Standing iron torch will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Standing iron torch / [piece_groundtorch_fuel_count_of_suppress_processing]
Suppresses automatic processing of Standing iron torch to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Refuel Standing iron torch Only When Out Of Fuel / [piece_groundtorch_refuel_only_when_out_of_fuel]
Performs automatic refuel only when Standing iron torch is out of fuel.

- Default value: false

==== Allow Processing By Standing wood torch / [allow_processing_by_piece_groundtorchwood]
Specify the automatic processing to be allowed for Standing wood torch

- Default value: Refuel
- Acceptable values: None, Refuel

==== Container Search Range By Standing wood torch / [container_search_range_by_piece_groundtorchwood]
Specify the maximum distance which Standing wood torch will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Fuel Count Of Suppress Processing For Standing wood torch / [piece_groundtorchwood_fuel_count_of_suppress_processing]
Suppresses automatic processing of Standing wood torch to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Refuel Standing wood torch Only When Out Of Fuel / [piece_groundtorchwood_refuel_only_when_out_of_fuel]
Performs automatic refuel only when Standing wood torch is out of fuel.

- Default value: false

==== Allow Processing By Stone oven / [allow_processing_by_piece_oven]
Specify the automatic processing to be allowed for Stone oven

- Default value: All
- Acceptable values: None, Craft, Refuel, Store, All
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Refuel)

==== Container Search Range By Stone oven / [container_search_range_by_piece_oven]
Specify the maximum distance which Stone oven will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Stone oven / [piece_oven_material_count_of_suppress_processing]
Suppresses automatic processing of Stone oven to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Product Stacks Of Suppress Processing For Stone oven / [piece_oven_product_stacks_of_suppress_processing]
Suppresses automatic processing of Stone oven to prevent the item stacks of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 99

==== Material Supply To Stone oven Only When Materials Run Out / [piece_oven_supply_only_when_materials_run_out]
Performs automatic craft only when materials of Stone oven run out.

- Default value: false

==== Fuel Count Of Suppress Processing For Stone oven / [piece_oven_fuel_count_of_suppress_processing]
Suppresses automatic processing of Stone oven to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Refuel Stone oven Only When Out Of Fuel / [piece_oven_refuel_only_when_out_of_fuel]
Performs automatic refuel only when Stone oven is out of fuel.

- Default value: false

==== Refuel Stone oven Only When Materials Supplied / [piece_oven_refuel_only_when_materials_supplied]
Performs automatic refuel only when materials are supplied to Stone oven.

- Default value: false

==== Allow Processing By Windmill / [allow_processing_by_piece_windmill]
Specify the automatic processing to be allowed for Windmill

- Default value: Store
- Acceptable values: None, Craft, Store
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Store)

==== Container Search Range By Windmill / [container_search_range_by_piece_windmill]
Specify the maximum distance which Windmill will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Windmill / [piece_windmill_material_count_of_suppress_processing]
Suppresses automatic processing of Windmill to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Product Stacks Of Suppress Processing For Windmill / [piece_windmill_product_stacks_of_suppress_processing]
Suppresses automatic processing of Windmill to prevent the item stacks of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 99

==== Material Supply To Windmill Only When Materials Run Out / [piece_windmill_supply_only_when_materials_run_out]
Performs automatic craft only when materials of Windmill run out.

- Default value: false

==== Allow Processing By Wisp fountain / [allow_processing_by_piece_wisplure]
Specify the automatic processing to be allowed for Wisp fountain

- Default value: Store
- Acceptable values: None, Store

==== Container Search Range By Wisp fountain / [container_search_range_by_piece_wisplure]
Specify the maximum distance which Wisp fountain will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Allow Processing By Sap extractor  / [allow_processing_by_piece_sapcollector]
Specify the automatic processing to be allowed for Sap extractor

- Default value: Store
- Acceptable values: None, Store

==== Container Search Range By Sap extractor  / [container_search_range_by_piece_sapcollector]
Specify the maximum distance which Sap extractor  will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Allow Processing By Eitr refinery / [allow_processing_by_piece_eitrrefinery]
Specify the automatic processing to be allowed for Eitr refinery

- Default value: Store
- Acceptable values: None, Craft, Refuel, Store, All
- Multiple values can be set at the same time by separating them with , (e.g. Craft, Refuel)

==== Container Search Range By Eitr refinery / [container_search_range_by_piece_eitrrefinery]
Specify the maximum distance which Eitr refinery will search for containers. (Unit: meter)

- Default value: 8
- Acceptable value range: From 1 to 64

==== Material Count Of Suppress Processing For Eitr refinery / [piece_eitrrefinery_material_count_of_suppress_processing]
Suppresses automatic processing of Eitr refinery to prevent the count of materials stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of materials.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Product Stacks Of Suppress Processing For Eitr refinery / [piece_eitrrefinery_product_stacks_of_suppress_processing]
Suppresses automatic processing of Eitr refinery to prevent the item stacks of products stored in a container from exceeding a specified quantity. Set to 0 to disable automatic processing suppression based on the count of products.

- Default value: 0
- Acceptable value range: From 0 to 99

==== Material Supply To Eitr refinery Only When Materials Run Out / [piece_eitrrefinery_supply_only_when_materials_run_out]
Performs automatic craft only when materials of Eitr refinery run out.

- Default value: false

==== Fuel Count Of Suppress Processing For Eitr refinery / [piece_eitrrefinery_fuel_count_of_suppress_processing]
Suppresses automatic processing of Eitr refinery to prevent the count of fuels stored in a container from falling below a specified quantity. Set to 0 to disable automatic processing suppression based on the count of fuels.

- Default value: 1
- Acceptable value range: From 0 to 999

==== Refuel Eitr refinery Only When Out Of Fuel / [piece_eitrrefinery_refuel_only_when_out_of_fuel]
Performs automatic refuel only when Eitr refinery is out of fuel.

- Default value: false

==== Refuel Eitr refinery Only When Materials Supplied / [piece_eitrrefinery_refuel_only_when_materials_supplied]
Performs automatic refuel only when materials are supplied to Eitr refinery.

- Default value: false

=== [ #6 Automatic Feeding ] / [automatic_feeding]
==== Disable Module / [module_disable]
You can disable this feature completely to avoid adding logic you don't need. (Game must be restart for reflect this option)

- Default value: false

==== Automatic Feeding / [enable_automatic_feeding]
Specify whether to enable the feature for animals to automatically consume feed items from players and containers.

- Default value: true

==== Feed Search Range / [feed_search_range]
Specify the range in which the animal searches for food. If set to 0, the default value for each animal will be used. (Unit: meter)

- Default value: 0
- Acceptable value range: From 0 to 64

==== Need Get Close To Eat The Feed / [need_get_close_to_eat_the_feed]
Specify whether the animal needs to approach the container or player to eat the feed.

- Default value: false

==== Allow To Feed From Container / [allow_to_feed_from_container]
Specify the types of animals allowed to feed from the container.

- Default value: Tamed
- Acceptable values: None, Wild, Tamed, All
- Multiple values can be set at the same time by separating them with , (e.g. Wild, Tamed)

==== Allow To Feed From Player / [allow_to_feed_from_player]
Specify the types of animals allowed to feed from the player inventory.

- Default value: None
- Acceptable values: None, Wild, Tamed, All
- Multiple values can be set at the same time by separating them with , (e.g. Wild, Tamed)

=== [ #7 Automatic Repair ] / [automatic_repair]
==== Disable Module / [module_disable]
You can disable this feature completely to avoid adding logic you don't need. (Game must be restart for reflect this option)

- Default value: false

==== Automatic Repair / [enable_automatic_repair]
Specify whether to enable the feature that automatically repair items and pieces.

- Default value: true

==== Crafting Station Search Range / [crafting_station_search_range]
Specify the range to search for a crafting station to be used to repair items. Setting to 0 disables periodic item repair. (Unit: meters)

- Default value: 16
- Acceptable value range: From 0 to 64

==== Repair Items When Accessing The Crafting Station / [repair_items_when_accessing_the_crafting_station]
Specify whether or not to repair all items that can be repaired when the workbench GUI is opened.

- Default value: false

==== Item Repair Message / [item_repair_message]
Specify where the message is displayed when an item is repaired.

- Default value: None
- Acceptable values: None, Center, TopLeft

==== Piece Search Range / [piece_search_range]
Specify the range to search for a pieces to repair. Setting to 0 disables periodic pieces repairs. (Unit: meters)

- Default value: 16
- Acceptable value range: From 0 to 64

==== Piece Repair Message / [piece_repair_message]
Specify where the message is displayed when a piece is repaired.

- Default value: None
- Acceptable values: None, Center, TopLeft

=== [ #8 Automatic Mining ] / [automatic_mining]
==== Disable Module / [module_disable]
You can disable this feature completely to avoid adding logic you don't need. (Game must be restart for reflect this option)

- Default value: false

==== Automatic Mining / [enable_automatic_mining]
Specify whether to enable the feature that mine minerals automatically.

- Default value: true

==== Mining Interval / [mining_interval]
Specify the interval between mining attempts. (Unit: seconds)

- Default value: 1.5
- Acceptable value range: From 0.1 to 4

==== Mining Range / [mining_range]
Specify the maximum distance to search for a mineral. Setting to 0 the pickaxe's attack range is used. (Unit: meters)

- Default value: 3
- Acceptable value range: From 0 to 32

==== Allow Mining Mineral / [allow_mining_mineral]
Specify the minerals to be automatically mined.

- Default value: CopperDeposit, TinDeposit, MudPile, ObsidianDeposit, SilverVein, PetrifiedBone, SoftTissue

==== Need To Equip Pickaxe For Mining / [need_to_equip_pickaxe]
Specify whether a pickaxe needs to be equipped to attempt automatic mining. Disabling this option will use the most advanced pickaxe in the player's inventory. If there is no pickaxe in the player's inventory, automatic mining will not be attempted.

- Default value: true

==== Allow Mining Underground Minerals / [allow_mining_underground_minerals]
Specify whether or not to allow mining underground minerals.

- Default value: true

==== Need To Wishbone For Mining Underground Minerals / [need_to_equip_wishbone_for_mining_underground_minerals]
Specify whether or not to require a wishbone to mine underground minerals.

- Default value: true

==== Attempt Mining / [mining_key]
Specify a shortcut key to attempt mining. If a valid shortcut key is assigned to this option, mining at regular intervals is disabled.

- Default value:

=== [ #9 Automatic Pickup ] / [automatic_pickup]
==== Disable Module / [module_disable]
You can disable this feature completely to avoid adding logic you don't need. (Game must be restart for reflect this option)

- Default value: false

==== Automatic Pickup Range / [automatic_pickup_range]
Specify the range within which objects are automatically pickup. (Unit: meters)

- Default value: 4
- Acceptable value range: From 1 to 64

==== Automatic Pickup Interval / [automatic_pickup_interval]
Specify the interval within which objects are automatically pickup. Setting it to 0 disables periodic automatic pickup. (Unit: second)

- Default value: 0.5
- Acceptable value range: From 0 to 4

==== Pickup All Nearby / [pickup_all_nearby_key]
Interacting with pickable objects using this key makes it possible to pick up the same object in a range at once. If a valid shortcut key is assigned to this option, pickup at regular intervals is disabled.

- Default value:
