= Automatics - Valheim Mod
:uri-configuration-manager: https://github.com/BepInEx/BepInEx.ConfigurationManager
:uri-litjson: https://litjson.net
:uri-license: link:LICENSE
:uri-config: link:CONFIG.adoc
:uri-custom_map_icons_example: link:/package/extra/custom-icon-example/Automatics/Textures
:uri-custom_map_icons_zip: https://app.box.com/shared/static/dv8vd8ls83rzxcsl75zrh9rawlu5o2w7.zip
:thumbnail-uri-config_menu: https://app.box.com/shared/static/3v57rjpauzzyv0xeugohnw8bn2ye3q2h.png
:image-uri-config_menu: https://app.box.com/shared/static/vfzsn69i950l48er2u69tssod6xxsh8u.jpg
:thumbnail-uri-custom_map_icon: https://app.box.com/shared/static/ggj61oyrdik1jk08lohdqr91e1q5isqv.png
:image-uri-custom_map_icon: https://app.box.com/shared/static/yhdd2v0mrwzgh54tbkc7twjen17q22gn.jpg

Automatics is a mod that automates the tedious tasks of life in Valheim. Most of its features exist in existing mods, but it has been re-designed to make it easier for me to use.

== Features
=== Automatic door
Automatically opens and closes the door near the player. The interval and distance to detect the player can be changed from the configuration.

=== Automatic map pinning
Automatic pinning animals, monsters, floras, veins, dungeons, etc. that exist around the player to the map. The pinning allows for each object and the detection range of the object can be changed from the config.

====

[discrete]
=== Custom map icons
Using png files and json, you can customize icons for pins added by Automatic map pinning.

image:{thumbnail-uri-custom_map_icon}[link={image-uri-custom_map_icon},title="Custom Map Icons (Click to view full size)"]

[discrete]
==== Directory structure

Place the necessary files in "/Valheim/BepInEx/plugins/Automatics/Textures" to make the custom icons work.

* */Valheim/BepInEx/plugins/Automatics/Textures*
  ** *custom-map-icon.json*
    *** Describe information such as which icons to customize and which images to use. Details are described in the <<format-of-custom-map-iconjson,Format of custom-map-icon.json>> section.
  ** *ICON.png*
    *** Icon image file. PNG files with transparency information are preferred. Prepare the number of icons required.

[discrete]
==== Format of custom-map-icon.json

Root <Array>::
  * target <Object>
    ** name <String>
      - Specify a display name such as "Boar" or an internal name such as "$enemy_boar"; See the <<Matching by "Display name" and "Internal name">> section for the difference between matching by display name and internal name.
    ** metadata <Object> (Optional)
      *** level <Number>
        - By setting up this field, you can set up icons for different levels of animals and monsters. Note that the unstarred state is level 1. One star is level 2 and two stars are level 3. Also, do not set the metada field if matching by level is not required.
  * sprite <Object>
    ** file <String>
      - Specify the name of the image file to be used for the icon. It is best to keep the image size between 16x16 and 32x32, as too large an icon will be obtrusive.
    ** width <Number>
      - Specify the width of the icon.
    ** height <Number>
      - Specify the height of the icon.

[discrete]
==== Example files
I don't feel I have explained it very well, so I have prepared a sample file. Please click {uri-custom_map_icons_example}[here] to check the structure of the file that actually works. You can also download the {uri-custom_map_icons_zip}[zip file] and check the operation on your PC.

- {uri-custom_map_icons_example}[Example files (Github)]
- {uri-custom_map_icons_zip}[Example files (Zip)]

NOTE: Zip is not guaranteed to work with mod loaders other than Vortex; if you are using a mod loader other than Vortex, please manually place the files in the Zip into the appropriate directory.

====

=== Automatic processing
Refueling pieces that need fuel. Deliver materials to pieces that process materials, and store items produced by pieces. These tasks can be automated via containers around the piece.

=== Automatic feeding
Animals and other creatures that consume food will be able to consume food from containers and the player's inventory, not just from food on the ground.

=== Automatic repair
It can automatically repair items when the player is near a crafting station or when the crafting station GUI is opened or automatically repair nearby pieces when the player has a hammer equipped.

== Console commands
Automatics add a few commands to help the user.

=== automatics [COMMAND]
Displays the usage of commands added by Automatics.

- COMMAND: Command name to display usage. If there is an exact match, it will be displayed. Otherwise, it will display the first partially matched command found. If omitted, the usage of the automatics command itself is displayed.

=== printnames (WORD|REGEXP)...
Outputs internal or display names that contain the specified string or match the specified regular expression. If multiple arguments are specified, only those matching all of them will be output.

- WORD: A text contained in the internal or display name. (e.g. $enemy_, $item_, $piece_, Boar, Mushroom, Wood door); All partially matching internal and display names are output.
- REGEXP: A regular expression of the internal or display name to be output. Must be prefixed with "r/". (e.g. r/^[$]item_, r/^boar$)

Examples:

- `printnames ling r/^[$]enemy_`
- `printnames r/^[$@]location_.+(?<!_(enter|exit))$`
- `printnames mushroom r/^[$]item_.+(?<!_description)$`

== Configurations
I recommend using {uri-configuration-manager}[Configuration Manager].

image:{thumbnail-uri-config_menu}[link={image-uri-config_menu},title="Configuration Menu (Click to view full size)"]

The README would be too large if we described all the details of the configuration, so we split it into separate file.

{uri-config}[Open CONFIG.adoc] to see the configuration details.

== Supplementary explanation
=== Matching by "Display name" and "Internal name"
In some features of Automatics, there is an option that allows the user to add targets as needed. The "Display name" and "Internal name" are used to identify these targets. The display name and internal name are matched according to different rules.

==== Display name
Display names are the names that appear in the game, such as Boar, Deer, Dandelion, etc. The matching rule for "Display name" is a partial match, meaning that if the target display name contains the specified string, it matches. It is case-insensitive.

==== Internal name
Internal names are the names used inside the game program, such as $enemy_boar, $enemy_deer, $item_dandelion, etc. The matching rule for "Internal name" is an exact match, meaning that if the target internal name is identical to the specified string, it matches. It is case-insensitive. Note that internal names for translations added by Automatics are prefixed with @, not $, as in `@internal_name`

==== Matching Samples
.Target data
[%header]
|===
| Display name | Internal name
| Greyling     | $enemy_greyling
| Greydwarf    | $enemy_greydwarf
| Surtling     | $enemy_surtling
|===

.Matching result
[%header]
|===
|           | Grey      | ling     | $enemy_greyling | $enemy_greydwarf | $enemy_
| Greyling  | Match     | Match    | Match           | No match         | No match
| Greydwarf | Match     | No match | No match        | Match            | No match
| Surtling  | No match  | Match    | No match        | No match         | No match
|===

== Languages
[%header]
|===
|Language |Translators       |Status
|English  |Translation Tools |100%
|Japanese |EideeHi           |100%
|===

== Credits
* Dependencies:
** {uri-configuration-manager}[Configuration Manager]
** {uri-litjson}[LitJSON]

== License
Automatics is developed and released under the MIT license. For the full text of the license, please see the {uri-license}[LICENSE] file.
